version: "3"

networks:
  substats_network:
    driver:
      bridge

services:
 
  substats:
    image: cesslab/substats:latest
    container_name: substats
    networks:
      - substats_network
    command: ["npm", "start"]
    restart: on-failure
    ports:
      - 8080:8080
    expose:
      - 8080
